import type { ItemType } from '../src/types/level';

function item(id: string, icon: string, kind: ItemType['kind'], defaultLabel: string) {
  return (label: string = defaultLabel): ItemType => ({ id, label, kind, icon });
}

// Reusable generic items for new levels (office/mall/forest and beyond). Icons are resolved
// through the SVG registry (import.meta.glob in iconRegistry.ts) — no ItemIcon.tsx cases needed.
// Generate bespoke ItemType objects only for items that are genuinely unique to a level's
// theme — check here first.
export const ItemLibrary = {
  // ——— Улица (26-street) ———
  car: item('car', 'car', 'occupiable', 'Машина'),
  trafficLight: item('trafficLight', 'trafficLight', 'decorative', 'Светофор'),
  trafficSign: item('trafficSign', 'trafficSign', 'decorative', 'Дорожный знак'),
  washer: item('washer', 'washingMachine', 'decorative', 'Стиральная машина'),
  // ——— Дом великана (27-gianthouse) ———
  kettle: item('kettle', 'kettle', 'decorative', 'Чайник'),
  fryingPan: item('fryingPan', 'fryingPan', 'occupiable', 'Сковорода'),
  burner: item('burner', 'burner', 'decorative', 'Конфорка'),
  pillow: item('pillow', 'pillow', 'occupiable', 'Подушка'),
  remote: item('remote', 'remote', 'decorative', 'Пульт'),
  plate: item('plate', 'plate', 'occupiable', 'Тарелка'),
  cup: item('cup', 'cup', 'decorative', 'Чашка'),
  slippers: item('slippers', 'slippers', 'decorative', 'Тапки'),
  cat: item('cat', 'cat', 'decorative', 'Кот'),
  // ——— Горный отель (28-skihotel) ———
  fireplace: item('fireplace', 'fireplace', 'decorative', 'Камин'),
  skiRack: item('skiRack', 'skiRack', 'decorative', 'Стойка с лыжами'),
  // ——— Цирк (29-circus) ———
  cage: item('cage', 'cage', 'decorative', 'Клетка'),
  hoop: item('hoop', 'hoop', 'decorative', 'Обруч'),
  turnstile: item('turnstile', 'turnstile', 'decorative', 'Турникет'),
  // ——— Дайнер (30-diner) ———
  jukebox: item('jukebox', 'jukebox', 'decorative', 'Музыкальный автомат'),
  booth: item('booth', 'booth', 'occupiable', 'Кабинка'),
  pieDisplay: item('pieDisplay', 'pieDisplay', 'decorative', 'Витрина с пирогами'),
  neonSign: item('neonSign', 'neonSign', 'decorative', 'Неоновая вывеска'),
  motorcycle: item('motorcycle', 'motorcycle', 'occupiable', 'Мотоцикл'),
  // ——— Полярная станция (31-polar) ———
  polarBear: item('polarBear', 'polarBear', 'decorative', 'Белый медведь'),
  igloo: item('igloo', 'igloo', 'decorative', 'Иглу'),
  snowmobile: item('snowmobile', 'snowmobile', 'occupiable', 'Снегоход'),
  radioStation: item('radioStation', 'radioStation', 'decorative', 'Радиостанция'),
  chair: item('chair', 'chair', 'occupiable', 'Стул'),
  armchair: item('armchair', 'armchair', 'occupiable', 'Кресло'),
  sofa: item('sofa', 'sofa', 'occupiable', 'Диван'),
  bench: item('bench', 'bench', 'occupiable', 'Скамейка'),
  stool: item('stool', 'stool', 'occupiable', 'Табурет'),
  workbench: item('workbench', 'workbench', 'occupiable', 'Рабочий стол'),
  plant: item('plant', 'plant', 'decorative', 'Растение'),
  globe: item('globe', 'globe', 'decorative', 'Глобус'),
  portrait: item('portrait', 'portrait', 'decorative', 'Портрет'),
  telescope: item('telescope', 'telescope', 'decorative', 'Телескоп'),
  bookshelf: item('bookshelf', 'bookshelf', 'decorative', 'Книжный шкаф'),
  box: item('box', 'box', 'decorative', 'Коробка'),
  rack: item('rack', 'rack', 'decorative', 'Стойка'),
  ladder: item('ladder', 'ladder', 'decorative', 'Стремянка'),
  lamppost: item('lamppost', 'lamppost', 'decorative', 'Фонарь'),
  trashcan: item('trashcan', 'trashcan', 'decorative', 'Урна'),
  barrel: item('barrel', 'barrel', 'decorative', 'Бочка'),
  safe: item('safe', 'safe', 'decorative', 'Сейф'),
  fountain: item('fountain', 'fountain', 'decorative', 'Фонтан'),
  kiosk: item('kiosk', 'kiosk', 'decorative', 'Киоск'),
  kassa: item('kassa', 'kassa', 'decorative', 'Касса'),
  piano: item('piano', 'piano', 'decorative', 'Пианино'),
  billiardTable: item('billiardTable', 'billiardTable', 'decorative', 'Бильярдный стол'),
  barStool: item('barStool', 'barStool', 'occupiable', 'Барный табурет'),
  hitchingPost: item('hitchingPost', 'hitchingPost', 'decorative', 'Коновязь'),
  souvenirRack: item('souvenirRack', 'souvenirRack', 'decorative', 'Стойка с сувенирами'),
  computer: item('computer', 'computer', 'decorative', 'Компьютер'),
  watercooler: item('watercooler', 'watercooler', 'decorative', 'Кулер с водой'),
  horse: item('horse', 'horse', 'occupiable', 'Лошадь'),
  cactus: item('cactus', 'cactus', 'decorative', 'Кактус'),
  wagon: item('wagon', 'wagon', 'decorative', 'Повозка'),
  trough: item('trough', 'trough', 'decorative', 'Корыто с водой'),
  goal: item('goal', 'goal', 'occupiable', 'Ворота'),
  ball: item('ball', 'ball', 'decorative', 'Мяч'),
  seat: item('seat', 'seat', 'occupiable', 'Сиденье трибуны'),
  treadmill: item('treadmill', 'treadmill', 'occupiable', 'Беговой тренажёр'),
  exerciseBike: item('exerciseBike', 'exerciseBike', 'occupiable', 'Велотренажёр'),
  hurdle: item('hurdle', 'hurdle', 'decorative', 'Барьер'),
  bed: item('bed', 'bed', 'occupiable', 'Койка'),
  table: item('table', 'table', 'decorative', 'Стол'),
  basketball: item('basketball', 'basketball', 'decorative', 'Баскетбольный мяч'),
  toilet: item('toilet', 'toilet', 'decorative', 'Туалет'),
  camera: item('camera', 'camera', 'decorative', 'Камера наблюдения'),
  toolbox: item('toolbox', 'toolbox', 'decorative', 'Ящик с инструментами'),
  clock: item('clock', 'clock', 'decorative', 'Часы'),
  bathtub: item('bathtub', 'bathtub', 'occupiable', 'Ванна'),
  jacuzzi: item('jacuzzi', 'jacuzzi', 'occupiable', 'Джакузи'),
  tv: item('tv', 'tv', 'decorative', 'Плазменный телевизор'),
  floorLamp: item('floorLamp', 'floorLamp', 'decorative', 'Торшер'),
  keyBox: item('keyBox', 'keyBox', 'decorative', 'Ящик с ключами'),
  journal: item('journal', 'journal', 'decorative', 'Журнал бронирований'),
  barCounter: item('barCounter', 'barCounter', 'decorative', 'Барная стойка'),
  palm: item('palm', 'palm', 'decorative', 'Пальма'),
  rock: item('rock', 'rock', 'decorative', 'Камень'),
  coconut: item('coconut', 'coconut', 'decorative', 'Кокос'),
  hammock: item('hammock', 'hammock', 'occupiable', 'Гамак'),
  hut: item('hut', 'hut', 'decorative', 'Бунгало'),
  bottle: item('bottle', 'bottle', 'decorative', 'Бутылка с письмом'),
  shell: item('shell', 'shell', 'decorative', 'Ракушка'),
  campfire: item('campfire', 'campfire', 'decorative', 'Костёр'),
  chest: item('chest', 'artifactChest', 'decorative', 'Сундук'),
  lamp: item('lamp', 'lamp', 'decorative', 'Маячная лампа'),
  boat: item('boat', 'boat', 'decorative', 'Ял'),
  tree: item('tree', 'tree', 'decorative', 'Ель'),
  stove: item('stove', 'stove', 'decorative', 'Печь'),
  fridge: item('fridge', 'fridge', 'decorative', 'Холодильник'),
  wardrobe: item('wardrobe', 'wardrobe', 'decorative', 'Шкаф'),
  suitcase: item('suitcase', 'suitcase', 'decorative', 'Чемодан'),
  berth: item('berth', 'berth', 'occupiable', 'Полка'),
  samovar: item('samovar', 'samovar', 'decorative', 'Самовар'),
  luggageRack: item('luggageRack', 'luggageRack', 'decorative', 'Багажная полка'),
  throne: item('throne', 'throne', 'occupiable', 'Трон'),
  candleStand: item('candleStand', 'candleStand', 'decorative', 'Подсвечник'),
  armorStand: item('armorStand', 'armorStand', 'decorative', 'Стойка с доспехом'),
  weaponRack: item('weaponRack', 'weaponRack', 'decorative', 'Стойка с оружием'),
  well: item('well', 'well', 'decorative', 'Колодец'),
  haystack: item('haystack', 'haystack', 'decorative', 'Стог сена'),
  ferrisWheel: item('ferrisWheel', 'ferrisWheel', 'occupiable', 'Колесо обозрения'),
  swing: item('swing', 'swing', 'occupiable', 'Качели'),
  carousel: item('carousel', 'carousel', 'occupiable', 'Карусель'),
  slide: item('slide', 'slide', 'occupiable', 'Горки'),
  plane: item('plane', 'plane', 'decorative', 'Самолёт'),
  windsock: item('windsock', 'windsock', 'decorative', 'Ветровой конус'),
  baggageCart: item('baggageCart', 'baggageCart', 'decorative', 'Тележка багажа'),
  lion: item('lion', 'lion', 'decorative', 'Лев'),
  giraffe: item('giraffe', 'giraffe', 'decorative', 'Жираф'),
  monkey: item('monkey', 'monkey', 'decorative', 'Обезьяна'),
  hippo: item('hippo', 'hippo', 'decorative', 'Бегемот'),
  zebra: item('zebra', 'zebra', 'decorative', 'Зебра'),
  penguin: item('penguin', 'penguin', 'decorative', 'Пингвин'),
  shootingGallery: item('shootingGallery', 'shootingGallery', 'decorative', 'Тир'),
  popcornStand: item('popcornStand', 'popcornStand', 'decorative', 'Стойка с попкорном'),
  clapperboard: item('clapperboard', 'clapperboard', 'decorative', 'Хлопушка'),
  spotlight: item('spotlight', 'spotlight', 'decorative', 'Прожектор'),
  makeupMirror: item('makeupMirror', 'makeupMirror', 'decorative', 'Гримёрное зеркало'),
  movieCamera: item('movieCamera', 'movieCamera', 'decorative', 'Кинокамера'),
  medicineCabinet: item('medicineCabinet', 'medicineCabinet', 'decorative', 'Шкаф с лекарствами'),
  clueBoard: item('clueBoard', 'clueBoard', 'decorative', 'Доска для записей'),
} satisfies Record<string, (label?: string) => ItemType>;
