import type { ItemType } from '../src/types/level';

type ItemOverrides = Partial<Omit<ItemType, 'id'>>;

function item(
  id: string,
  icon: string,
  kind: ItemType['kind'],
  defaultLabel: string,
  defaults: ItemOverrides = {},
) {
  return (label: string = defaultLabel, overrides: ItemOverrides = {}): ItemType => ({
    id,
    label,
    kind,
    icon,
    ...defaults,
    ...overrides,
  });
}

// Canonical ItemType factory catalog for every level. Icons are resolved through the SVG registry
// (import.meta.glob in iconRegistry.ts), and level-specific variants can override factory defaults.
export const ItemLibrary = {
  // ——— Предметы, ранее объявлявшиеся локально в уровнях ———
  flowerbed: item('flowerbed', 'flowerbed', 'decorative', 'Клумба'),
  tent: item('tent', 'tent', 'decorative', 'Палатка'),
  stump: item('stump', 'stump', 'decorative', 'Пень'),
  cauldron: item('cauldron', 'cauldron', 'decorative', 'Котёл'),
  spellbookStand: item('spellbookStand', 'spellbookStand', 'decorative', 'Стойка с заклинаниями'),
  broomRack: item('broomRack', 'broomRack', 'decorative', 'Стойка мётел'),
  mannequin: item('mannequin', 'mannequin', 'decorative', 'Манекен'),
  cart: item('cart', 'cart', 'decorative', 'Тележка'),
  paintingStand: item('paintingStand', 'paintingStand', 'decorative', 'Стенд с картиной'),
  sculpture: item('sculpture', 'sculpture', 'decorative', 'Скульптура на постаменте'),
  examTable: item('examTable', 'examTable', 'occupiable', 'Смотровой стол'),
  sarcophagus: item('sarcophagus', 'sarcophagus', 'decorative', 'Саркофаг'),
  canopicJar: item('canopicJar', 'canopicJar', 'decorative', 'Канопа'),
  torch: item('torch', 'torch', 'decorative', 'Факел'),
  goldStatue: item('goldStatue', 'goldStatue', 'decorative', 'Золотая статуя'),
  stela: item('stela', 'stela', 'decorative', 'Стела'),
  airlock: item('airlock', 'airlock', 'decorative', 'Шлюзовой люк'),
  satelliteDish: item('satelliteDish', 'satelliteDish', 'decorative', 'Спутниковая тарелка'),
  cryopod: item('cryopod', 'cryopod', 'decorative', 'Криокапсула'),
  console: item('console', 'computer', 'occupiable', 'Пульт управления'),
  departureBoard: item('departureBoard', 'departureBoard', 'decorative', 'Табло отправления'),
  tumbleweed: item('tumbleweed', 'tumbleweed', 'decorative', 'Перекати-поле'),
  royalChest: item('royalChest', 'artifactChest', 'decorative', 'Королевский сундук'),
  royalBed: item('royalBed', 'bed', 'occupiable', 'Королевское ложе'),
  linenBox: item('linenBox', 'box', 'decorative', 'Ящик с бельём'),
  ballReturn: item('ballReturn', 'ballReturn', 'decorative', 'Возвратник шаров'),
  pins: item('pins', 'pins', 'decorative', 'Кегли'),
  bowlingBall: item('bowlingBall', 'bowlingBall', 'decorative', 'Шар для боулинга'),
  pickaxe: item('pickaxe', 'pickaxe', 'decorative', 'Кирка'),
  minecart: item('minecart', 'minecart', 'occupiable', 'Вагонетка'),
  jackhammer: item('jackhammer', 'jackhammer', 'decorative', 'Отбойный молоток'),
  punchingBag: item('punchingBag', 'punchingBag', 'decorative', 'Боксёрская груша'),
  ringCorner: item('ringCorner', 'ringCorner', 'decorative', 'Стойка ринга'),
  boxingGloves: item('boxingGloves', 'boxingGloves', 'decorative', 'Боксёрские перчатки'),
  reactorVat: item('reactorVat', 'reactorVat', 'decorative', 'Реакторный чан'),
  testTubeRack: item('testTubeRack', 'testTubeRack', 'decorative', 'Стеллаж с пробирками'),
  trailer: item('trailer', 'trailer', 'occupiable', 'Трейлер'),
  tombstone: item('tombstone', 'tombstone', 'decorative', 'Надгробие'),
  freshGrave: item('freshGrave', 'freshGrave', 'decorative', 'Свежая могила'),
  cemeteryGate: item('cemeteryGate', 'cemeteryGate', 'decorative', 'Ворота кладбища'),
  bushHedge: item('bushHedge', 'bushHedge', 'decorative', 'Куст', { render: 'tile' }),
  roseBush: item('roseBush', 'roseBush', 'decorative', 'Розовый куст', { render: 'tile' }),
  grapeVine: item('grapeVine', 'grapeVine', 'decorative', 'Виноградная лоза', { render: 'tile', tileEdgeDepth: false }),
  winePress: item('winePress', 'winePress', 'decorative', 'Винный пресс'),
  grapeCrate: item('grapeCrate', 'grapeCrate', 'decorative', 'Ящик винограда'),
  wineRack: item('wineRack', 'wineRack', 'decorative', 'Стойка для вина'),
  fineDiningTable: item('fineDiningTable', 'fineDiningTable', 'decorative', 'Стол со скатертью'),
  kitchenIsland: item('kitchenIsland', 'kitchenIsland', 'decorative', 'Кухонный остров'),
  waiterTrolley: item('waiterTrolley', 'waiterTrolley', 'decorative', 'Тележка официанта'),
  servingCloche: item('servingCloche', 'servingCloche', 'decorative', 'Блюдо под колпаком'),
  flowerVase: item('flowerVase', 'flowerVase', 'decorative', 'Ваза с цветами'),
  wineGlass: item('wineGlass', 'wineGlass', 'decorative', 'Бокал вина'),
  iceCream: item('iceCream', 'iceCream', 'decorative', 'Мороженое'),
  tennisRacket: item('tennisRacket', 'tennisRacket', 'decorative', 'Теннисная ракетка'),
  tennisBall: item('tennisBall', 'tennisBall', 'decorative', 'Теннисный мяч'),
  tennisNet: item('tennisNet', 'tennisNet', 'decorative', 'Теннисная сетка', { render: 'span' }),
  anchorWinch: item('anchorWinch', 'anchorWinch', 'decorative', 'Носовая лебёдка'),
  flowerArch: item('flowerArch', 'flowerArch', 'decorative', 'Цветочная арка'),
  weddingCake: item('weddingCake', 'weddingCake', 'decorative', 'Свадебный торт'),
  barbecue: item('barbecue', 'barbecue', 'decorative', 'Барбекю'),
  laundryLine: item('laundryLine', 'laundryLine', 'decorative', 'Бельё на верёвке'),
  breadDisplay: item('breadDisplay', 'breadDisplay', 'decorative', 'Витрина с хлебом'),
  pastryDisplay: item('pastryDisplay', 'pastryDisplay', 'decorative', 'Кондитерская витрина'),
  convectionOven: item('convectionOven', 'convectionOven', 'decorative', 'Конвекционная печь'),
  croissant: item('croissant', 'croissant', 'decorative', 'Круассан'),
  coffeeMachine: item('coffeeMachine', 'coffeeMachine', 'decorative', 'Кофемашина'),
  gondola: item('gondola', 'gondola', 'occupiable', 'Кабина канатной дороги'),
  cable: item('cable', 'cable', 'decorative', 'Трос канатной дороги', { render: 'tile', tileEdgeDepth: false }),
  cableSupport: item('cableSupport', 'cableSupport', 'decorative', 'Опора канатной дороги'),
  stationSign: item('stationSign', 'station', 'decorative', 'Станционный павильон'),
  fish: item('fish', 'fish', 'decorative', 'Рыба', { render: 'span' }),
  crab: item('crab', 'crab', 'decorative', 'Краб'),
  seaweed: item('seaweed', 'seaweed', 'decorative', 'Водоросли', { render: 'tile', tileEdgeDepth: false }),
  consoleSetup: item('consoleSetup', 'consoleSetup', 'occupiable', 'Игровая приставка'),
  arcadeCabinet: item('arcadeCabinet', 'arcadeCabinet', 'decorative', 'Аркадный автомат'),
  outhouseToilet: item('outhouseToilet', 'outhouseToilet', 'occupiable', 'Деревенский туалет'),
  golfHole: item('golfHole', 'golfHole', 'decorative', 'Лунка с флажком'),
  golfTee: item('golfTee', 'golfTee', 'decorative', 'Ти с мячом'),
  golfBag: item('golfBag', 'golfBag', 'decorative', 'Сумка для клюшек'),
  golfCart: item('golfCart', 'golfCart', 'occupiable', 'Гольф-кар'),
  saxophone: item('saxophone', 'saxophone', 'decorative', 'Саксофон'),
  drumKit: item('drumKit', 'drumKit', 'occupiable', 'Барабанная установка'),
  cigar: item('cigar', 'cigar', 'decorative', 'Сигара'),
  // ——— Полицейский участок (65-policestation) ———
  policeBadge: item('policeBadge', 'policeBadge', 'decorative', 'Полицейский значок'),
  handcuffs: item('handcuffs', 'handcuffs', 'decorative', 'Наручники'),
  evidenceBag: item('evidenceBag', 'evidenceBag', 'decorative', 'Пакет улик'),
  // ——— Улица (26-street) ———
  car: item('car', 'car', 'occupiable', 'Машина'),
  fuelPump: item('fuelPump', 'fuelPump', 'decorative', 'Топливная колонка'),
  carWashBrush: item('carWashBrush', 'carWashBrush', 'decorative', 'Щётка автомойки'),
  gasPriceSign: item('gasPriceSign', 'gasPriceSign', 'decorative', 'Табло цен'),
  carJack: item('carJack', 'carJack', 'decorative', 'Домкрат'),
  trafficLight: item('trafficLight', 'trafficLight', 'decorative', 'Светофор'),
  trafficSign: item('trafficSign', 'trafficSign', 'decorative', 'Дорожный знак'),
  washer: item('washer', 'washingMachine', 'decorative', 'Стиральная машина'),
  // ——— Дом великана (27-gianthouse) ———
  kettle: item('kettle', 'kettle', 'decorative', 'Чайник'),
  fryingPan: item('fryingPan', 'fryingPan', 'decorative', 'Сковорода'),
  burner: item('burner', 'burner', 'decorative', 'Конфорка'),
  pillow: item('pillow', 'pillow', 'occupiable', 'Подушка'),
  remote: item('remote', 'remote', 'decorative', 'Пульт'),
  plate: item('plate', 'plate', 'decorative', 'Тарелка'),
  cup: item('cup', 'cup', 'decorative', 'Чашка'),
  slippers: item('slippers', 'slippers', 'decorative', 'Тапки'),
  cat: item('cat', 'cat', 'decorative', 'Кот'),
  // ——— Горный отель (28-skihotel) ———
  fireplace: item('fireplace', 'fireplace', 'decorative', 'Камин'),
  skiRack: item('skiRack', 'skiRack', 'decorative', 'Стойка с лыжами'),
  // ——— Цирк (29-circus) ———
  cage: item('cage', 'cage', 'decorative', 'Клетка'),
  hoop: item('hoop', 'hoop', 'decorative', 'Обруч'),
  turnstile: item('turnstile', 'turnstile', 'decorative', 'Турникет'),
  // ——— Дайнер (30-diner) ———
  jukebox: item('jukebox', 'jukebox', 'decorative', 'Музыкальный автомат'),
  booth: item('booth', 'booth', 'occupiable', 'Кабинка'),
  pieDisplay: item('pieDisplay', 'pieDisplay', 'decorative', 'Витрина с пирогами'),
  neonSign: item('neonSign', 'neonSign', 'decorative', 'Неоновая вывеска'),
  motorcycle: item('motorcycle', 'motorcycle', 'occupiable', 'Мотоцикл'),
  // ——— Полярная станция (31-polar) ———
  polarBear: item('polarBear', 'polarBear', 'decorative', 'Белый медведь'),
  igloo: item('igloo', 'igloo', 'decorative', 'Иглу'),
  snowmobile: item('snowmobile', 'snowmobile', 'occupiable', 'Снегоход'),
  radioStation: item('radioStation', 'radioStation', 'decorative', 'Радиостанция'),
  // ——— Курорт (45-resort) ———
  inflatableMattress: item('inflatableMattress', 'inflatableMattress', 'occupiable', 'Надувной матрас'),
  sunLounger: item('sunLounger', 'sunLounger', 'occupiable', 'Шезлонг'),
  beachChair: item('beachChair', 'beachChair', 'occupiable', 'Пляжный стульчик'),
  bathrobe: item('bathrobe', 'bathrobe', 'decorative', 'Халат'),
  beachUmbrella: item('beachUmbrella', 'beachUmbrella', 'decorative', 'Пляжный зонт'),
  // ——— Телестудия (46-tvstudio) ———
  directorConsole: item('directorConsole', 'directorConsole', 'decorative', 'Режиссёрский пульт'),
  studioSoftbox: item('studioSoftbox', 'studioSoftbox', 'decorative', 'Софтбокс'),
  newsDesk: item('newsDesk', 'newsDesk', 'decorative', 'Стол ведущего'),
  // ——— Пираты (32-pirates) ———
  wheel: item('wheel', 'wheel', 'occupiable', 'Штурвал'),
  cannon: item('cannon', 'cannon', 'decorative', 'Пушка'),
  parrot: item('parrot', 'parrot', 'decorative', 'Попугай'),
  lifebuoy: item('lifebuoy', 'lifebuoy', 'occupiable', 'Спасательный круг'),
  lifeboat: item('lifeboat', 'boat', 'occupiable', 'Шлюпка'),
  // ——— Гонки в городе (33-racing) ———
  raceCar: item('raceCar', 'raceCar', 'occupiable', 'Гоночная машина'),
  yacht: item('yacht', 'yacht', 'occupiable', 'Яхта'),
  monument: item('monument', 'monument', 'decorative', 'Памятник победителю'),
  townhouse: item('townhouse', 'townhouse', 'decorative', 'Городской дом'),
  tireStack: item('tireStack', 'tireStack', 'decorative', 'Стопка покрышек'),
  // ——— Казино (34-casino) ———
  slotMachine: item('slotMachine', 'slotMachine', 'decorative', 'Игровой автомат'),
  rouletteTable: item('rouletteTable', 'rouletteTable', 'occupiable', 'Стол для рулетки'),
  pokerTable: item('pokerTable', 'pokerTable', 'occupiable', 'Стол для покера'),
  // ——— Бойцовский клуб (40-fightclub) ———
  locker: item('locker', 'locker', 'decorative', 'Шкафчик'),
  // ——— Музыкальный фестиваль (36-festival) ———
  guitar: item('guitar', 'guitar', 'decorative', 'Гитара'),
  micStand: item('micStand', 'micStand', 'decorative', 'Стойка с микрофоном'),
  speaker: item('speaker', 'speaker', 'decorative', 'Колонка'),
  veggieCounter: item('veggieCounter', 'veggieCounter', 'decorative', 'Овощной прилавок'),
  chair: item('chair', 'chair', 'occupiable', 'Стул'),
  armchair: item('armchair', 'armchair', 'occupiable', 'Кресло'),
  sofa: item('sofa', 'sofa', 'occupiable', 'Диван'),
  bench: item('bench', 'bench', 'occupiable', 'Скамейка'),
  stool: item('stool', 'stool', 'occupiable', 'Табурет'),
  workbench: item('workbench', 'workbench', 'occupiable', 'Рабочий стол'),
  plant: item('plant', 'plant', 'decorative', 'Растение'),
  gardenBed: item('gardenBed', 'gardenBed', 'decorative', 'Грядка'),
  globe: item('globe', 'globe', 'decorative', 'Глобус'),
  portrait: item('portrait', 'portrait', 'decorative', 'Портрет'),
  telescope: item('telescope', 'telescope', 'decorative', 'Телескоп'),
  bookshelf: item('bookshelf', 'bookshelf', 'decorative', 'Книжный шкаф'),
  box: item('box', 'box', 'decorative', 'Коробка'),
  rack: item('rack', 'rack', 'decorative', 'Стойка'),
  ladder: item('ladder', 'ladder', 'decorative', 'Стремянка'),
  lamppost: item('lamppost', 'lamppost', 'decorative', 'Фонарь'),
  trashcan: item('trashcan', 'trashcan', 'decorative', 'Урна'),
  barrel: item('barrel', 'barrel', 'decorative', 'Бочка'),
  safe: item('safe', 'safe', 'decorative', 'Сейф'),
  fountain: item('fountain', 'fountain', 'decorative', 'Фонтан'),
  kiosk: item('kiosk', 'kiosk', 'decorative', 'Киоск'),
  kassa: item('kassa', 'kassa', 'decorative', 'Касса'),
  piano: item('piano', 'piano', 'decorative', 'Пианино'),
  billiardTable: item('billiardTable', 'billiardTable', 'decorative', 'Бильярдный стол'),
  barStool: item('barStool', 'barStool', 'occupiable', 'Барный табурет'),
  hitchingPost: item('hitchingPost', 'hitchingPost', 'decorative', 'Коновязь'),
  souvenirRack: item('souvenirRack', 'souvenirRack', 'decorative', 'Стойка с сувенирами'),
  computer: item('computer', 'computer', 'decorative', 'Компьютер'),
  watercooler: item('watercooler', 'watercooler', 'decorative', 'Кулер с водой'),
  horse: item('horse', 'horse', 'occupiable', 'Лошадь'),
  cactus: item('cactus', 'cactus', 'decorative', 'Кактус'),
  wagon: item('wagon', 'wagon', 'decorative', 'Повозка'),
  trough: item('trough', 'trough', 'decorative', 'Корыто с водой'),
  goal: item('goal', 'goal', 'occupiable', 'Ворота'),
  ball: item('ball', 'ball', 'decorative', 'Мяч'),
  seat: item('seat', 'seat', 'occupiable', 'Сиденье трибуны'),
  treadmill: item('treadmill', 'treadmill', 'occupiable', 'Беговой тренажёр'),
  exerciseBike: item('exerciseBike', 'exerciseBike', 'occupiable', 'Велотренажёр'),
  hurdle: item('hurdle', 'hurdle', 'decorative', 'Барьер'),
  bed: item('bed', 'bed', 'occupiable', 'Койка'),
  table: item('table', 'table', 'decorative', 'Стол'),
  basketball: item('basketball', 'basketball', 'decorative', 'Баскетбольный мяч'),
  toilet: item('toilet', 'toilet', 'decorative', 'Туалет'),
  camera: item('camera', 'camera', 'decorative', 'Камера наблюдения'),
  toolbox: item('toolbox', 'toolbox', 'decorative', 'Ящик с инструментами'),
  clock: item('clock', 'clock', 'decorative', 'Часы'),
  bathtub: item('bathtub', 'bathtub', 'occupiable', 'Ванна'),
  jacuzzi: item('jacuzzi', 'jacuzzi', 'occupiable', 'Джакузи'),
  tv: item('tv', 'tv', 'decorative', 'Плазменный телевизор'),
  floorLamp: item('floorLamp', 'floorLamp', 'decorative', 'Торшер'),
  keyBox: item('keyBox', 'keyBox', 'decorative', 'Ящик с ключами'),
  journal: item('journal', 'journal', 'decorative', 'Журнал бронирований'),
  barCounter: item('barCounter', 'barCounter', 'decorative', 'Барная стойка'),
  palm: item('palm', 'palm', 'decorative', 'Пальма'),
  rock: item('rock', 'rock', 'decorative', 'Камень'),
  coconut: item('coconut', 'coconut', 'decorative', 'Кокос'),
  hammock: item('hammock', 'hammock', 'occupiable', 'Гамак'),
  hut: item('hut', 'hut', 'decorative', 'Бунгало'),
  bottle: item('bottle', 'bottle', 'decorative', 'Бутылка с письмом'),
  shell: item('shell', 'shell', 'decorative', 'Ракушка'),
  campfire: item('campfire', 'campfire', 'decorative', 'Костёр'),
  pants: item('pants', 'pants', 'decorative', 'Штаны'),
  saunaStove: item('saunaStove', 'saunaStove', 'decorative', 'Каменка'),
  washTub: item('washTub', 'washTub', 'decorative', 'Таз'),
  towel: item('towel', 'towel', 'decorative', 'Полотенце'),
  venik: item('venik', 'venik', 'decorative', 'Веник'),
  chest: item('chest', 'artifactChest', 'decorative', 'Сундук'),
  lamp: item('lamp', 'lamp', 'decorative', 'Маячная лампа'),
  boat: item('boat', 'boat', 'decorative', 'Ял'),
  tree: item('tree', 'tree', 'decorative', 'Ель'),
  broadleafTree: item('broadleafTree', 'broadleafTree', 'decorative', 'Лиственное дерево'),
  stove: item('stove', 'stove', 'decorative', 'Печь'),
  fridge: item('fridge', 'fridge', 'decorative', 'Холодильник'),
  fireExtinguisher: item('fireExtinguisher', 'fireExtinguisher', 'decorative', 'Огнетушитель'),
  wardrobe: item('wardrobe', 'wardrobe', 'decorative', 'Шкаф'),
  suitcase: item('suitcase', 'suitcase', 'decorative', 'Чемодан'),
  berth: item('berth', 'berth', 'occupiable', 'Полка'),
  samovar: item('samovar', 'samovar', 'decorative', 'Самовар'),
  luggageRack: item('luggageRack', 'luggageRack', 'decorative', 'Багажная полка'),
  throne: item('throne', 'throne', 'occupiable', 'Трон'),
  candleStand: item('candleStand', 'candleStand', 'decorative', 'Подсвечник'),
  armorStand: item('armorStand', 'armorStand', 'decorative', 'Стойка с доспехом'),
  weaponRack: item('weaponRack', 'weaponRack', 'decorative', 'Стойка с оружием'),
  well: item('well', 'well', 'decorative', 'Колодец'),
  haystack: item('haystack', 'haystack', 'decorative', 'Стог сена'),
  ferrisWheel: item('ferrisWheel', 'ferrisWheel', 'occupiable', 'Колесо обозрения'),
  swing: item('swing', 'swing', 'occupiable', 'Качели'),
  carousel: item('carousel', 'carousel', 'occupiable', 'Карусель'),
  slide: item('slide', 'slide', 'occupiable', 'Горки'),
  plane: item('plane', 'plane', 'decorative', 'Самолёт'),
  windsock: item('windsock', 'windsock', 'decorative', 'Ветровой конус'),
  baggageCart: item('baggageCart', 'baggageCart', 'decorative', 'Тележка багажа'),
  lion: item('lion', 'lion', 'decorative', 'Лев'),
  giraffe: item('giraffe', 'giraffe', 'decorative', 'Жираф'),
  monkey: item('monkey', 'monkey', 'decorative', 'Обезьяна'),
  hippo: item('hippo', 'hippo', 'decorative', 'Бегемот'),
  zebra: item('zebra', 'zebra', 'decorative', 'Зебра'),
  penguin: item('penguin', 'penguin', 'decorative', 'Пингвин'),
  shootingGallery: item('shootingGallery', 'shootingGallery', 'decorative', 'Тир'),
  popcornStand: item('popcornStand', 'popcornStand', 'decorative', 'Стойка с попкорном'),
  clapperboard: item('clapperboard', 'clapperboard', 'decorative', 'Хлопушка'),
  spotlight: item('spotlight', 'spotlight', 'decorative', 'Прожектор'),
  makeupMirror: item('makeupMirror', 'makeupMirror', 'decorative', 'Гримёрное зеркало'),
  movieCamera: item('movieCamera', 'movieCamera', 'decorative', 'Кинокамера'),
  medicineCabinet: item('medicineCabinet', 'medicineCabinet', 'decorative', 'Шкаф с лекарствами'),
  clueBoard: item('clueBoard', 'clueBoard', 'decorative', 'Доска для записей'),
  // ——— Парикмахерская (48-barbershop) ———
  barberChair: item('barberChair', 'barberChair', 'occupiable', 'Парикмахерское кресло'),
  hairDryer: item('hairDryer', 'hairDryer', 'decorative', 'Фен'),
  productShelf: item('productShelf', 'productShelf', 'decorative', 'Стойка с косметикой'),
  portableRadio: item('portableRadio', 'portableRadio', 'decorative', 'Переносная рация'),
  bicycle: item('bicycle', 'bicycle', 'decorative', 'Велосипед'),
  garland: item('garland', 'garland', 'decorative', 'Гирлянда'),
} satisfies Record<string, (label?: string, overrides?: ItemOverrides) => ItemType>;
